### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by denzardten** [saifalisew1508/Telegram-Members-Adder#31]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Telegram-Members-Adder-main\Telegram-Members-Adder-main\add.py", line 74, in <module>
    accounts.append(pickle.load(f))
                    ^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by cosanostratr** [comment]
up

**Comment by saifalisew1508** [comment]
@cosanostratr Yeah You Should Use latest version https://github.com/saifalisew1508/TelegramAdderTool

**Comment by firminofir** [comment]
Traceback (most recent call last):
  File "C:\Users\cliente\Desktop\Telegram-Members-Adder-main\manager.py", line 48, in <module>
    banner()
  File "C:\Users\cliente\Desktop\Telegram-Members-Adder-main\manager.py", line 37, in banner
    print(f'{lg}Version: {w}2.0{lg} | GitHub: {w}@saifalisew1508{rs}')
